spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/freecoupon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Dnjfchs23

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  jwt:
    secret: bXlmcmVlY291cG9uCg==
    token-header: "Authorization"
    token-prefix: "Bearer "

qr-api: https://chart.apis.google.com/chart?cht=qr&chs=300x300&chl=
qr-server: http://127.0.0.1:8080/partner/check-coupon/